### ISSUE TITLE
Links do not  work in Wiki

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-online-permitting#25]
Christmas Tree Module and Special Use Module Liver version links in Wiki under Project Cope repositories do not work

**Comment by lauraGgit** [comment]
Thanks @aaronburk.

Fyi, probably makes sense for us to just point to our master so for xmas:
[Christmas Tree Module](https://forest-service-epermit.app.cloud.gov/christmas-trees/forests)
[Special Use](https://forest-service-epermit.app.cloud.gov/christmas-trees/forests)
