### ISSUE TITLE
Naming Open Forest Platform is broken

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-online-permitting#29]
When you click the Naming open forest link in the right menu it goes to the main Wiki page

**Comment by hannahkane** [comment]
Fixed!

How I fixed it:
I checked the list of pages on the wiki 
![naming the epermits platform 18f fs online permitting wiki](https://user-images.githubusercontent.com/8389648/44216589-19e5f780-a12a-11e8-9784-b8d96f91a7db.png)

to find the correct link, and was able to edit it using github's web editing interface.

Let me know if you'd like a quick walk-through of how to do this!
